### ISSUE TITLE
Support for custom graphics placed in a "graphics" subdirectory

### ISSUE THREAD

**Issue by Hoeloe** [WohlSoft/PGE-Project#262] opened 2018-07-17 13:53 UTC
SMBX2b4 adds the option to put episode or level graphics inside "graphics" subdirectories, structured like the basegame directories. This helps organisation for projects with large amounts of custom graphics. These graphics currently do not show in the editor.

**Comment by Wohlstand** [comment] 2018-07-17 13:55
Can be easily supported on Engine side, however, on Editor side this will become as memory usage hell. Therefore, Editor side is dependent on this: https://github.com/WohlSoft/PGE-Project/issues/244.

**Comment by Wohlstand** [comment] 2018-07-17 13:57
Just now I have found, this is duplicate of #206 issue.

**Closed by Wohlstand** 2018-07-17 13:57 UTC
Labels: Graphics, Priority - ultra
